name: CD
on:
  workflow_dispatch:
  workflow_run:
    workflows: [formatting] # TODO switch to CI once made
    types: [completed]

concurrency: ${{ github.workflow }}

jobs:
  deploy-infra:
    # If CD was triggered by a CI run
    # ensure that the CI run was actually successful
    if: ${{ github.event.type != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: true
      matrix:
        env: [dev] # TODO add prod here

    runs-on: ubuntu-latest
    environment:
      name: infra/${{ matrix.env }}
      url: ${{ matrix.env == 'prod' && 'https://login.walletconnect.com/health' || format('https://{0}.login.walletconnect.com/health', matrix.env) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: deploy-${{ matrix.env }}
        uses: WalletConnect/actions/actions/deploy-terraform/@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          environment: ${{ matrix.env }}
