name: terraform_plan

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: plan
        uses: WalletConnect/actions/actions/plan-terraform/@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          environment: dev
          app-name: ${{ github.event.repository.name }}
      - uses: actions/upload-artifact@v3
        with:
          name: plan.tfplan
          path: ${{ steps.plan.outputs.plan-file }}
      - uses: actions/upload-artifact@v3
        with:
          name: plan.txt
          path: ${{ steps.plan.outputs.output-file }}
      - name: Add Plan to PR
        uses: actions/github-script@v6
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.plan }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `<details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
